version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  jobs:
    post_create_environment:
      - python -m pip install poetry==2.1.3
    post_install:
      - VIRTUAL_ENV=$READTHEDOCS_VIRTUALENV_PATH poetry install --only main,docs
    pre_build:
      - make docs-pre-build

sphinx:
   configuration: docs/src/conf.py

