#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# developer.skatelescope.org documentation build configuration file, created by
# sphinx-quickstart on Wed Dec 13 11:59:38 2017.
#
# This file is execfile()d with the current directory set to its
# containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
import os
import sys

sys.path.insert(0, os.path.abspath("../.."))
sys.path.append(os.path.abspath("../../src"))


def setup(app):
    app.add_css_file('custom.css')

# -- Project information -------------------------------------------------

project = "SKA SDP Instrumental Calibration Pipeline"
copyright = "2025, SKA Organization"
author = "Team YABBY, Team DHRUVA"
release = "0.6.0"
version = "0.6.0"

# -- General configuration ------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#
# needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    'sphinx.ext.autodoc',
    'sphinx.ext.napoleon',
    'sphinx.ext.doctest',
    'sphinx.ext.intersphinx',
    'sphinx.ext.todo',
    'sphinx.ext.coverage',
    'sphinx.ext.mathjax',
    'sphinx.ext.ifconfig',
    'sphinx.ext.viewcode',
    'sphinx.ext.githubpages',
    'recommonmark',
    "ska_sdp_piper.extensions.sphinx_piper_stage",
    "sphinx_autodoc_typehints",
]

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
source_suffix = {
    '.rst': 'restructuredtext',
    '.md': 'markdown',
}

# List of modules to mock
autodoc_mock_imports = [
    'everybeam',
    'casacore',
    'ska_sdp_func',
]

# The master toctree document.
master_doc = 'index'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = 'En-en'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This patterns also effect to html_static_path and html_extra_path
exclude_patterns = []

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = True


# -- Options for HTML output ----------------------------------------------

# The theme to use for HTML and HTML Help pages.

html_theme = "ska_ser_sphinx_theme"
html_static_path = ['_static']
html_context = {}
latex_elements = {}


# Example configuration for intersphinx: refer to the Python standard library.
intersphinx_mapping = {
    "dask": ("https://docs.dask.org/en/stable", None),
    "numpy": ("https://numpy.org/doc/stable", None),
    "python": ("https://docs.python.org/3", None),
    "xarray": ("https://docs.xarray.dev/en/stable", None),
    "astropy": ("https://docs.astropy.org/en/stable/", None),
    "ska_sdp_piper": ("https://developer.skao.int/projects/ska-sdp-exec-piper/en/latest/", None),
    "ska_sdp_datamodels": ("https://developer.skao.int/projects/ska-sdp-datamodels/en/latest/", None),
}

# Ensure that functions are documented as they are 
# present in the source code
autodoc_member_order = 'bysource'

# Disable smart quoting
smartquotes = False

# Configurations for sphinx_autodoc_typehints
typehints_defaults = "comma"
always_use_bars_union = True