import h5py
import numpy as np
from ska_sdp_datamodels.calibration.calibration_model import GainTable

from ...logger import setup_logger
from ...xarray_processors.delay import DelayTable
from ..h5parm import (
    create_clock_soltab_datasets,
    create_soltab_datasets,
    create_soltab_group,
    to_null_terminated_bytes,
)

logger = setup_logger(__name__)


def export_gaintable_to_h5parm(
    gaintable: GainTable,
    filename: str,
    exclude_cross_pols: bool = False,
    squeeze: bool = False,
):
    """
    Export a GainTable to a H5Parm file.
    H5Parm is a HDf5 file, with schema specific to
    LOFAR software (losoto, DP3)

    NOTE: The exported data is slightly different than the input
    gaintable data, in following ways:
    1. The gaintable 'gain' are set to 'nan', where gaintable 'weight' is 0.

    In short, this function treats the gaintable 'weight' as flags.
    This can be revisited in the future once we understand the meaning
    behind 'weight' values generated by solvers.

    Parameters
    ----------
    gaintable
        Gaintable instance
    filename
        Name of H5Parm file
    exclude_cross_pols
        if True, remove cross pols from dataset
    squeeze
        If True, remove axes of length one from dataset
    """
    logger.info(f"exporting cal solutions to {filename}")

    # check gaintable gain and weight dimensions
    dims = ["time", "antenna", "frequency", "receptor1", "receptor2"]
    if list(gaintable.gain.sizes) != dims:
        raise ValueError(f"Unexpected dims: {list(gaintable.gain.sizes)}")

    # adjust dimensions to be consistent with H5Parm output format
    gaintable = gaintable.rename({"antenna": "ant", "frequency": "freq"})
    gaintable = gaintable.stack(pol=("receptor1", "receptor2"))
    polstrs = to_null_terminated_bytes(
        [f"{p1}{p2}" for p1, p2 in gaintable["pol"].data]
    )
    gaintable = gaintable.drop_vars(
        ["pol", "receptor1", "receptor2"]
    ).assign_coords({"pol": polstrs})

    # check polarisations and discard unused terms
    polstrs = to_null_terminated_bytes(["XX", "XY", "YX", "YY"])
    if not np.array_equal(gaintable["pol"].data, polstrs):
        raise ValueError("Subsequent pipelines assume linear pol order")

    # replace antenna indices with antenna names
    if gaintable.configuration is None:
        raise ValueError("Missing gt config. H5Parm requires antenna names")
    antenna_names = to_null_terminated_bytes(
        gaintable.configuration.names.data[gaintable["ant"].data]
    )
    gaintable = gaintable.assign_coords({"ant": antenna_names})

    # Flag gains where weight == 0
    gaintable_gain = gaintable["gain"].where(
        gaintable["weight"] != 0, np.nan, drop=False
    )

    gaintable = gaintable.assign(gain=gaintable_gain)

    # remove cross pols if not required
    if exclude_cross_pols:
        gaintable = gaintable.isel(pol=[0, 3])

    # remove axes of length one if required
    if squeeze:
        gaintable = gaintable.squeeze(drop=True)

    logger.info(f"output dimensions: {dict(gaintable.gain.sizes)}")

    with h5py.File(filename, "w") as file:

        solset = file.create_group("sol000")

        # Amplitude table
        soltab = create_soltab_group(solset, "amplitude")
        val, weight = create_soltab_datasets(soltab, gaintable)
        val[...] = np.absolute(gaintable["gain"].data)
        weight[...] = gaintable["weight"].data

        # Phase table
        soltab = create_soltab_group(solset, "phase")
        val, weight = create_soltab_datasets(soltab, gaintable)
        val[...] = np.angle(gaintable["gain"].data)
        weight[...] = gaintable["weight"].data


def export_clock_to_h5parm(
    delaytable: DelayTable, filename: str, squeeze: bool = False
):
    """
    Export delaytable Dataset to a H5Parm HDF5 file.

    Parameters
    ----------
    delaytable
        Xarray dataset representing the delay table. Similar to gaintable
    filename
        Name of H5Parm file
    squeeze
        If True, remove axes of length one from dataset
    """
    logger.info(f"exporting cal solutions to {filename}")

    # check delaytable gain and weight dimensions
    dims = ["time", "antenna", "pol"]
    if list(delaytable.delay.sizes) != dims:
        raise ValueError(f"Unexpected dims: {list(delaytable.delay.sizes)}")

    # adjust dimensions to be consistent with H5Parm output format
    delaytable = delaytable.rename({"antenna": "ant"})

    if not np.array_equal(delaytable.pol.data, ["XX", "YY"]):
        raise ValueError("Subsequent pipelines assume linear pol order")

    polstrs = to_null_terminated_bytes(delaytable.pol.data)
    delaytable = delaytable.assign_coords({"pol": polstrs})

    # replace antenna indices with antenna names
    if delaytable.configuration is None:
        raise ValueError("Missing gt config. H5Parm requires antenna names")

    antenna_names = to_null_terminated_bytes(
        delaytable.configuration.names.data[delaytable["ant"].data]
    )
    delaytable = delaytable.assign_coords({"ant": antenna_names})

    # remove axes of length one if required
    if squeeze:
        delaytable = delaytable.squeeze(drop=True)

    logger.info(f"output dimensions: {dict(delaytable.delay.sizes)}")

    with h5py.File(filename, "w") as file:

        solset = file.create_group("sol000")

        soltab = create_soltab_group(solset, "clock")
        val, offset = create_clock_soltab_datasets(soltab, delaytable)
        val[...] = delaytable["delay"].data
        offset[...] = delaytable["offset"].data
