from typing import Iterable, Literal

import h5py
import numpy as np
import xarray as xr
from numpy.typing import NDArray

from ...logger import setup_logger
from ...xarray_processors.delay import DelayTable
from ..schema.calibration_set import GainCalibrationSetXds

logger = setup_logger("data_managers.data_export")


def create_soltab_group(
    solset: h5py.Group, solution_type: Literal["amplitude", "phase", "clock"]
) -> h5py.Group:
    """Create soltab group under given solset group.

    :param solset: base-level HDF5 group to update
    :param solution_type: only "amplitude" and "phase" are supported at present
    :return: HDF5 group for the "solution_type" data
    """
    soltab = solset.create_group(f"{solution_type}000")
    soltab.attrs["TITLE"] = np.bytes_(solution_type)
    return soltab


def create_soltab_datasets(
    soltab: h5py.Group, gaintable: GainCalibrationSetXds
):
    """Add a dataset for each of the GainCalibrationSetXds dimensions.

    :param soltab: HDF5 table to update
    :param gaintable: GainCalibrationSetXds
    """
    # create a dataset for each dimension
    for dim in list(gaintable.CALPARAM_GAIN.sizes):
        soltab.create_dataset(dim, data=gaintable[dim].data)

    # create datasets for the data and weights
    shape = gaintable.CALPARAM_GAIN.shape
    axes = np.bytes_(",".join(list(gaintable.CALPARAM_GAIN.sizes)))

    val = soltab.create_dataset("val", shape=shape, dtype=float)
    val.attrs["AXES"] = axes

    weight = soltab.create_dataset("weight", shape=shape, dtype=float)
    weight.attrs["AXES"] = axes

    return val, weight


def create_clock_soltab_datasets(soltab: h5py.Group, delaytable: xr.Dataset):
    """Add a dataset for each of the Delay dimensions.

    :param soltab: HDF5 table to update
    :param delaytable: xr.Dataset
    """
    # create a dataset for each dimension
    for dim in list(delaytable.delay.sizes):
        soltab.create_dataset(dim, data=delaytable[dim].data)

    # create datasets for the data and weights
    shape = delaytable.delay.shape
    axes = np.bytes_(",".join(list(delaytable.delay.sizes)))

    val = soltab.create_dataset("val", shape=shape, dtype=float)
    val.attrs["AXES"] = axes

    offset = soltab.create_dataset("offset", shape=shape, dtype=float)
    offset.attrs["AXES"] = axes

    return val, offset


def _ndarray_of_null_terminated_bytes(strings: Iterable[str]) -> NDArray:
    # NOTE: making antenna names one character longer, in keeping with
    # ska-sdp-batch-preprocess
    return np.asarray([s.encode("ascii") + b"\0" for s in strings])


def export_gaintable_to_h5parm(
    gaintable: GainCalibrationSetXds,
    filename: str,
    exclude_cross_pols: bool = False,
    squeeze: bool = False,
):
    """
    Export a GainCalibrationSetXds to a H5Parm file.
    H5Parm is a HDf5 file, with schema specific to
    LOFAR software (losoto, DP3)

    NOTE: The exported data is slightly different than the input
    gaintable data, in following ways:
    1. The gaintable 'gain' are set to 'nan', where gaintable 'weight' is 0.

    In short, this function treats the gaintable 'weight' as flags.
    This can be revisited in the future once we understand the meaning
    behind 'weight' values generated by solvers.

    Parameters
    ----------
    gaintable
        Gaintable instance
    filename
        Name of H5Parm file
    exclude_cross_pols
        if True, remove cross pols from dataset
    squeeze
        If True, remove axes of length one from dataset
    """
    logger.info(f"exporting cal solutions to {filename}")

    # check gaintable gain and weight dimensions
    dims = [
        "time",
        "antenna_name",
        "frequency",
        "receptor_label1",
        "receptor_label2",
    ]
    if list(gaintable.CALPARAM_GAIN.sizes) != dims:
        raise ValueError(
            f"Unexpected dims: {list(gaintable.CALPARAM_GAIN.sizes)}"
        )

    # adjust dimensions to be consistent with H5Parm output format
    gaintable = gaintable.rename({"antenna_name": "ant", "frequency": "freq"})
    gaintable = gaintable.stack(pol=("receptor_label1", "receptor_label2"))
    polstrs = _ndarray_of_null_terminated_bytes(
        [f"{p1}{p2}" for p1, p2 in gaintable["pol"].data]
    )
    gaintable = gaintable.drop_vars(
        ["pol", "receptor_label1", "receptor_label2"]
    ).assign_coords({"pol": polstrs})

    # check polarisations and discard unused terms
    polstrs = _ndarray_of_null_terminated_bytes(["XX", "XY", "YX", "YY"])
    if not np.array_equal(gaintable["pol"].data, polstrs):
        raise ValueError("Subsequent pipelines assume linear pol order")

    # replace antenna indices with antenna names
    if gaintable["ant"].isnull().all():
        raise ValueError("Missing gt config. H5Parm requires antenna names")
    antenna_names = _ndarray_of_null_terminated_bytes(gaintable["ant"].data)
    gaintable = gaintable.assign_coords({"ant": antenna_names})

    # Flag gains where weight == 0
    gaintable_gain = gaintable["CALPARAM_GAIN"].where(
        gaintable["CALPARAM_WEIGHT"] != 0, np.nan, drop=False
    )

    gaintable = gaintable.assign(CALPARAM_GAIN=gaintable_gain)

    # remove cross pols if not required
    if exclude_cross_pols:
        gaintable = gaintable.isel(pol=[0, 3])

    # remove axes of length one if required
    if squeeze:
        gaintable = gaintable.squeeze(drop=True)

    logger.info(f"output dimensions: {dict(gaintable.CALPARAM_GAIN.sizes)}")

    with h5py.File(filename, "w") as file:

        solset = file.create_group("sol000")

        # Amplitude table
        soltab = create_soltab_group(solset, "amplitude")
        val, weight = create_soltab_datasets(soltab, gaintable)
        val[...] = np.absolute(gaintable["CALPARAM_GAIN"].data)
        weight[...] = gaintable["CALPARAM_WEIGHT"].data

        # Phase table
        soltab = create_soltab_group(solset, "phase")
        val, weight = create_soltab_datasets(soltab, gaintable)
        val[...] = np.angle(gaintable["CALPARAM_GAIN"].data)
        weight[...] = gaintable["CALPARAM_WEIGHT"].data


def export_clock_to_h5parm(
    delaytable: DelayTable, filename: str, squeeze: bool = False
):
    """
    Export delaytable Dataset to a H5Parm HDF5 file.

    Parameters
    ----------
    delaytable
        Xarray dataset representing the delay table. Similar to gaintable
    filename
        Name of H5Parm file
    squeeze
        If True, remove axes of length one from dataset
    """
    logger.info(f"exporting cal solutions to {filename}")

    # check delaytable gain and weight dimensions
    dims = ["time", "antenna", "pol"]
    if list(delaytable.delay.sizes) != dims:
        raise ValueError(f"Unexpected dims: {list(delaytable.delay.sizes)}")

    # adjust dimensions to be consistent with H5Parm output format
    delaytable = delaytable.rename({"antenna": "ant"})

    if not np.array_equal(delaytable.pol.data, ["XX", "YY"]):
        raise ValueError("Subsequent pipelines assume linear pol order")

    polstrs = _ndarray_of_null_terminated_bytes(delaytable.pol.data)
    delaytable = delaytable.assign_coords({"pol": polstrs})

    # replace antenna indices with antenna names
    if delaytable.configuration is None:
        raise ValueError("Missing gt config. H5Parm requires antenna names")

    antenna_names = _ndarray_of_null_terminated_bytes(
        delaytable.configuration.names.data[delaytable["ant"].data]
    )
    delaytable = delaytable.assign_coords({"ant": antenna_names})

    # remove axes of length one if required
    if squeeze:
        delaytable = delaytable.squeeze(drop=True)

    logger.info(f"output dimensions: {dict(delaytable.delay.sizes)}")

    with h5py.File(filename, "w") as file:

        solset = file.create_group("sol000")

        soltab = create_soltab_group(solset, "clock")
        val, offset = create_clock_soltab_datasets(soltab, delaytable)
        val[...] = delaytable["delay"].data
        offset[...] = delaytable["offset"].data
