parameters:
  load_data:
    nchannels_per_chunk: 64
    ntimes_per_ms_chunk: 20
    cache_directory: null
    ack: false
    datacolumn: DATA
    field_id: 0
    data_desc_id: 0
  predict_vis:
    beam_type: everybeam
    normalise_at_beam_centre: true
    eb_ms: null
    gleamfile: null
    lsm_csv_path: null
    export_sky_model: true
    element_response_model: oskar_dipole_cos
    fov: 10.0
    flux_limit: 1.0
    alpha0: -0.78
  bandpass_initialisation:
    refant: 0
    niter: 200
    tol: 1.0e-06
    export_gaintable: true
  bandpass_calibration:
    run_solver_config:
      solver: jones_substitution
      refant: 0
      niter: 50
      phase_only: false
      tol: 0.0001
      crosspol: false
    plot_config:
      plot_table: true
      fixed_axis: false
    visibility_key: vis
    export_gaintable: true
  delay_calibration:
    oversample: 1
    plot_config:
      plot_table: true
      fixed_axis: false
    export_gaintable: true
  export_gain_table:
    file_name: inst.gaintable
    export_format: h5parm
    export_metadata: false
pipeline:
  load_data: true
  predict_vis: true
  bandpass_initialisation: true
  bandpass_calibration: true
  delay_calibration: true
  flag_gain: false
  ionospheric_delay: false
  generate_channel_rm: false
  smooth_gain_solution: false
  export_visibilities: false
  export_gain_table: true
global_parameters:
  experimental:
    pipeline: []
