global_parameters:
  experimental:
    pipeline: []
parameters:
  load_data:
    nchannels_per_chunk: 16
  bandpass_initialisation:
    export_gaintable: false
  bandpass_calibration:
    plot_config:
      plot_table: false
      fixed_axis: false
    export_gaintable: false
  delay_calibration:
    plot_config:
      plot_table: false
      fixed_axis: false
    export_gaintable: false
  export_gain_table:
    file_name: gaintable
    export_format: h5parm
    export_metadata: false
pipeline:
  load_data: true
  predict_vis: true
  bandpass_initialisation: true
  bandpass_calibration: true
  delay_calibration: true
  flag_gain: false
  ionospheric_delay: false
  generate_channel_rm: false
  smooth_gain_solution: false
  export_visibilities: false
  export_gain_table: true
