global_parameters:
  experimental:
    pipeline: []
parameters:
  load_data:
    nchannels_per_chunk: 64
    ntimes_per_ms_chunk: 20
  predict_vis:
    fov: 10.0
    flux_limit: 1.0
pipeline:
  load_data: true
  predict_vis: true
  bandpass_initialisation: true
  bandpass_calibration: true
  delay_calibration: true
  flag_gain: false
  ionospheric_delay: false
  generate_channel_rm: false
  smooth_gain_solution: false
  export_visibilities: false
  export_gain_table: true
